# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testQuant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField()),
                ('content', models.TextField()),
                ('finish_flag', models.IntegerField(verbose_name='\u662f\u5426\u7ed3\u675f')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offtesset', models.IntegerField()),
                ('content', models.TextField()),
                ('finish_flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_return', models.FloatField(null=True)),
                ('basic_return', models.FloatField(null=True)),
                ('alpha', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('sharp', models.FloatField(null=True)),
                ('maxdown', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('parameter', models.CharField(max_length=255)),
                ('taskType', models.IntegerField(verbose_name='\u4efb\u52a1\u7c7b\u578b,0\u662f\u7f16\u8bd1,1\u662f\u56de\u6d4b')),
                ('status', models.IntegerField(verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.Policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.Task'),
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.Task'),
        ),
        migrations.AddField(
            model_name='current_result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.Task'),
        ),
    ]
