# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQuant', '0002_auto_20160511_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='offtesset',
            new_name='offset',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.CharField(default='\u8fd9\u4e2a\u5bb6\u4f19\u5f88\u61d2\uff0c\u4ec0\u4e48\u90fd\u6ca1\u7559\u4e0b', max_length=255),
        ),
    ]
