# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testQuant', '0004_auto_20160513_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontsize', models.CharField(default='14', max_length=10)),
                ('theme', models.CharField(default='monokai', max_length=20)),
                ('wropmode', models.CharField(default='false', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testQuant.UserProfile')),
            ],
        ),
    ]
