# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQuant', '0006_userprofile_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_path',
            field=models.CharField(default='/static/head-image/default.jpg', max_length=128),
        ),
    ]
