# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testQuant', '0007_auto_20160517_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplieError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField()),
                ('error_content', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQuant.Task')),
            ],
        ),
    ]
